[package]
name = "sw-graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
graphql_client = "0.12.0"
reqwest = { version = "0.11.14", features = ["json"] }
serde = "1.0.152"
tokio = { version = "^1", features = ["net", "rt-multi-thread", "macros"] }

